### ISSUE TITLE
Support helm plugins properly

### ISSUE THREAD

**Issue by mickmcgrath13** [bitops-plugins/helm#5]
the bitops config has [this section](https://github.com/bitops-plugins/helm/blob/main/bitops.schema.yaml#L74-L85):
```
    plugins:
      type: object
      properties:
        s3:
          type: object
          properties:
            region:
              type: string
              export_env: HELM_PLUGIN_S3_REGION
            bucket:
              type: string
              export_env: HELM_CHARTS_S3_BUCKET
```

2 things:
## 1. ops repo config
the block above suggests that it's configurable at the ops repo level. @PhillypHenning @armab can either of you confirm that `${plugin}.plugins` (e.g. `helm.plugins`) is respected from the core?  This would be used when the helm chart s3 bucket's region is different from the default region specified during bitops container startup.  ..or at least the `HELM_PLUGIN_S3_REGION` would. I think the `HELM_CHARTS_S3_BUCKET` one is superfluous because you include the s3 bucket name when referencing an s3 hosted chart in the `Chart.yaml` dependencies like:
```
apiVersion: v2
name: staffing-app wrapper
description: A Helm chart wrapper for the staffing app charts
version: 0.1.0

dependencies:
- name: app-staffing
  version: 0.1.2
  repository: s3://bitovi-operations-staffing-app-helm/charts
```

## 2. plugin install
The [install script](https://github.com/bitops-plugins/helm/blob/main/install.sh#L35) should probably be updated to allow arbitrary plugin installation (should be configured in the [plugin.config.yaml](https://github.com/bitops-plugins/helm/blob/main/plugin.config.yaml)
